[build-system]
requires = [
  "setuptools>=42",
  'setuptools<72.2; implementation_name == "pypy"', # https://github.com/pypa/distutils/issues/283
  "setuptools_scm[toml]>=3.4",
]

[tool.black]
target_version = ["py310"]

[tool.isort]
profile = "black"
known_first_party = ["ujson"]
